import Typography from "@mui/material/Typography";

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

const Home = () => {

    return (
        <Typography variant="h2">Hello, dear client</Typography>
    );
};

export default Home;